services:

    ##########################################
    # BNC HELPERS
    ##########################################

    bnc_core.candidate_helper:
        class: BNC\CoreBundle\Service\CandidateHelper
        #arguments:
        #    - "@service_container"
        #    - "@sitetheory_core.env"